### ISSUE TITLE
PasswordResetService provider uses default laravel database connectioj

### ISSUE THREAD

**Issue by izziaraffaele** [atrauzzi/laravel-doctrine#100]
I'm using laravel-doctrine in my project where I'm trying to implement reset password functionalities but actually the framework is creating a connection with the database using ConnectionFactory->createConnector that throws an error 

```
InvalidArgumentException in ConnectionFactory.php line 189:
Unsupported driver [pdo_mysql]
```

**Comment by josenicomaia** [comment]
Are you using laravel-doctrine?

**Comment by josenicomaia** [comment]
I am afraid there is not an integration for PasswordResetService today.

**Comment by izziaraffaele** [comment]
I solved creating my own PasswordResets doctrine's entity + repository and changing a bit the default PasswordResetServiceProvider in a way that loads my repository instead of let Laravel creating its own.

**Comment by josenicomaia** [comment]
Great Job! Are you planning to do a PR?

**Comment by izziaraffaele** [comment]
I'm doing things really fast because of a deadline with a client. As soon as I finish with it I'll make a PR with proper code and testing.

**Comment by josenicomaia** [comment]
Relax haha

**Comment by josenicomaia** [comment]
@izziaraffaele I guess you can close this one =]
