### ISSUE TITLE
SURVEY: Most commonly used version?

### ISSUE THREAD

**Issue by FoxxMD** [atrauzzi/laravel-doctrine#109]
Hello users of atrauzzi/laravel-doctrine!

We are working on a new package for laravel/doctrine integration and are writing a script that will be used to convert configuration files from atrauzzi/laravel-doctrine to this new package. Word on the street is that configuration files have changed enough between versions that we can't write just one template to cover all users.

So this issue is a survey to find out what version of laravel-doctrine you are using. What version do you use? 

If we don't get enough input on a common version we will support the latest version.

Thanks!

**Comment by FoxxMD** [comment]
We're going to ahead with the latest version if there's no input from users...

**Comment by atrauzzi** [comment]
Safe bet at this point ;)

**Comment by FoxxMD** [comment]
Thanks @atrauzzi!
