### ISSUE TITLE
Update readme to point to laravel-doctrine/orm

### ISSUE THREAD

**Issue by FoxxMD** [atrauzzi/laravel-doctrine#121]
Hi @atrauzzi,

I made a PR in [mitchellvanw](https://github.com/mitchellvanw/laravel-doctrine/pull/143)'s repo because they literally disappeared but you are still somewhat active here so I wanted to make a polite request to you rather than rudely vandalizing your readme in a PR ;)

Would you consider updating your readme to point to [our package](https://github.com/laravel-doctrine/orm) as an upgrade option from your package (and for new users looking for a laravel-doctrine solution) ? 

We have recently released [1.0](https://github.com/laravel-doctrine/orm/releases) and we have a more complete feature-set, an active dev team and support, and are still improving our codebase. The library draws inspiration from yours and mitchell's so upgrading is relatively painless and I even built a [configuration converter](http://www.laraveldoctrine.org/docs/1.0/orm/upgrade) to help with the process :)

**Comment by atrauzzi** [comment]
Hey!  I'll tell you what...  I'm totally okay with sorta "deprecating" this library and putting the new library's branding in here just to seal the deal.

Submit a PR and put anything you want at the top!

**Comment by atrauzzi** [comment]
(for anyone reading, if you're using this library, feel free to continue helping maintain it for your existing applications)
