### ISSUE TITLE
How to be compatible with Eloquent?

### ISSUE THREAD

**Issue by rochapablo** [atrauzzi/laravel-doctrine#125]
I'm getting this error:

> Declaration of Atrauzzi\LaravelDoctrine\Util\Time::setCreatedAt() should be compatible with Illuminate\Database\Eloquent\Model::setCreatedAt($value)

**Comment by atrauzzi** [comment]
While I'll still accept PRs for this project, it is no longer being actively maintained.  Please see the new Laravel Doctrine libary here: https://github.com/laravel-doctrine/orm

**Comment by rochapablo** [comment]
Ok! Thank you.
