### ISSUE TITLE
How to trigger orm commands

### ISSUE THREAD

**Issue by ensensis** [atrauzzi/laravel-doctrine#26]
I need generate my proxies manually, since Doctrine 2 documentation suggest to do:

```
doctrine orm:generate-proxies
```

I mean, after a fresh install of this package, how can I make use of doctrine cli-command?

**Comment by manfredjb** [comment]
I tried to emulate this script at Laravel 5, but I do not know  how to extract the EM from $app object:

```php
require __DIR__.'/bootstrap/autoload.php';

/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';
```

**Comment by morfin** [comment]
php artisan doctrine:generate:proxies
