### ISSUE TITLE
Error On Installing PackageNot Nound

### ISSUE THREAD

**Issue by mohammadmojrian** [atrauzzi/laravel-doctrine#27]
Problem 1
    - Installation request for atrauzzi/laravel-doctrine dev-master -> satisfiable by atrauzzi/laravel-doctrine[dev-master].
    - atrauzzi/laravel-doctrine dev-master requires doctrine/migrations 1.0.*@dev -> no matching package found.

**Comment by jurosh** [comment]
this means that package is not ready for production ?

**Comment by atrauzzi** [comment]
It means the Doctrine dependency isn't.

**Comment by jurosh** [comment]
but isn't possible to use some stable version of doctrine ?
