### ISSUE TITLE
Explicity set "devMode" for the package

### ISSUE THREAD

**Issue by manfredjb** [atrauzzi/laravel-doctrine#33]
I work with xCache. In the default package config it has:

    $devMode = $config->get('app.debug');

If it is set to "false", I am not able to work/debug xCache when the entire appliation is in "Debug" mode because of the following conditional:

    if(!$devMode) {
        $cache_config = $config->get('laravel-doctrine::doctrine.cache');
	$cache_provider = $cache_config['provider'];
	$cache_provider_config = $cache_config[$cache_provider];
    ....

My recommendation is to allow us to set explicity the "devMode" mode just for this package.

**Comment by atrauzzi** [comment]
If you'd like, you can submit a PR against the 1.x branch for this to get support for this functionality in Laravel 4.  Would just be a matter of adding it to the default config file and updating the service provider to prefer it from there.
