### ISSUE TITLE
Support for Laravel 5

### ISSUE THREAD

**Issue by ensensis** [atrauzzi/laravel-doctrine#42]
Hello Alexander, Laravel 5 is coming soon and some of us are playing around with this version from now. But looks like this module is not compatible yet. Will we see this module supported for Laravel 5?
Thank you.

**Comment by atrauzzi** [comment]
Done!

**Comment by manfredjb** [comment]
Hello @atrauzzi, 
I have 3 projects using your package for L4. Today I made a composer update and what is the surprise? looks like there is not support for L4 any more from this package. Is this right?

**Comment by atrauzzi** [comment]
Yeah, dev-master is now for Laravel 5, however you can still access the old version by choosing the 1.x series for your version.

Check out packagist for more information: https://packagist.org/packages/atrauzzi/laravel-doctrine

**Comment by manfredjb** [comment]
Thank you so much!  ... and following :)
