### ISSUE TITLE
DB Schema through notations? 

### ISSUE THREAD

**Issue by andrewmclagan** [atrauzzi/laravel-doctrine#44]
Their are other options to Doctrine migrations other then the comments notations system.

I do not like this system as it does not integrate well with any IDE and autocomplete and is outside of normal paradigms.

Doctrine can also use YAML or XML based schemas / migrations as i understand...

**Comment by atrauzzi** [comment]
It isn't XML or YAML, but the latest version designed for Laravel 5 supports loading mappings via config files.

Additional drivers would be fairly easy to add, I just don't have need of them right away.

**Comment by andrewmclagan** [comment]
I will actually do that! but not for a couple weeks sorry :-)

**Comment by atrauzzi** [comment]
Not a problem.  Let me know if you have any questions.

**Comment by joshjwalker** [comment]
I would love to work on implementing the YAML and XML solutions. I actually did it for the last version, but never did a pull request. Although, this version is more abstracted then the last version, so I have to figure out how you'd prefer me to handle the different cases.

**Comment by joshjwalker** [comment]
Would it not look almost exactly like the newAnnotationDriver method in the Configuration class, expect with YAML and XML drivers?
