### ISSUE TITLE
Comparing Doctine packages

### ISSUE THREAD

**Issue by joshhornby** [atrauzzi/laravel-doctrine#51]
Out of interest are there any differences between the two packages?

This one seems to be a little more active, hence why I am asking

https://github.com/mitchellvanw/laravel-doctrine

**Comment by atrauzzi** [comment]
I think overall they're comparable as any integration of Doctrine is best kept generic so as not to interfere with core features on either side.  I've gone to some effort to provide an array-style configuration syntax for your mappings if you don't want to use annotations.  You can also use annotations if you so desire.

The current version of my package is Laravel 5.0 ready.  I receive commits still and am happy to manage merge requests from the community.

The other package has made some progress into offering implementations of certain Laravel and Doctrine specific features.  Not such that it's impossible to catch up feature-wise, I just have yet to have need for them and have not received any feature requests for say.. a user provider, which is usually best implemented in your project, not a pacakge.

To that end, it's clear the two packages differ slightly on some details as to where the responsibilities lie and how to use dependency injection & service providers (I'm a bit more explicit).
