### ISSUE TITLE
Can't Find doctrine/migrations Package

### ISSUE THREAD

**Issue by CWSpear** [atrauzzi/laravel-doctrine#55]
When I try to install your package, I get this error from composer:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for atrauzzi/laravel-doctrine dev-master -> satisfiable by atrauzzi/laravel-doctrine[dev-master].
    - atrauzzi/laravel-doctrine dev-master requires doctrine/migrations dev-master#46a031ddaea47d0685200027cfe8c83b02aee6f6 -> no matching package found.
```

It appears that it cannot find the version of `doctrine/migrations` you have tagged in your `composer.json`. I'd create a PR, but I'm not sure why you tagged that specific version of `doctrine/migrations`...

**Comment by afibanez** [comment]
Same problem here

**Comment by afibanez** [comment]
Ok, i resolved it, and that issue has another ticket closed.

You have to write in composer.json:

    ...
	"type": "project",
	-> "minimum-stability": "dev",
	.> "prefer-stable": true,
	"require": {
     ...

And run again composer update
