### ISSUE TITLE
Authentification driver: doctrine

### ISSUE THREAD

**Issue by jurosh** [atrauzzi/laravel-doctrine#64]
Are you planning to add default authentication driver ?
/*
	|--------------------------------------------------------------------------
	| Default Authentication Driver
	|--------------------------------------------------------------------------
	|
	| This option controls the authentication driver that will be utilized.
	| This driver manages the retrieval and authentication of the users
	| attempting to get access to protected areas of your application.
	|
	| Supported: "database", "eloquent"
	|
	*/

	'driver' => 'doctrine',

**Comment by atrauzzi** [comment]
I'd be happy to merge a pull request for one, I can't imagine it's too complex.  I don't have the time at the moment to complete this.

I'll keep this issue open until either I get around to it or someone else offers.

**Comment by manfredjb** [comment]
My authentification driver is using this package, I could share it

**Comment by josenicomaia** [comment]
@manfredjb +1 =]

**Comment by rochapablo** [comment]
So?

**Comment by atrauzzi** [comment]
Check out https://github.com/laravel-doctrine/orm .
