### ISSUE TITLE
Problem with phpunit tests

### ISSUE THREAD

**Issue by asantanacu** [atrauzzi/laravel-doctrine#67]
I am having this error message when try to run more than one unit test in my laravel project at the same time
    "Doctrine\DBAL\DBALException: Type json already exists."
I found the error is in line 24 in file src/ServiceProvider
     Type::addType('json', '\Atrauzzi\LaravelDoctrine\Type\Json');
I dont know if this is the better way but for the moment I am solving it asking first if the type json already exists
      if (!Type::hasType("json"))
            Type::addType('json', '\Atrauzzi\LaravelDoctrine\Type\Json');

**Comment by jjunqueira** [comment]
I am having the same issue...It looks like the laravel application service providers are being initialized multiple times or something. So what happens is inside the Atrauzzi\LaravelDoctrine\ServiceProvider boot() function this line is being executed more than once:
```php
Type::addType('json', '\Atrauzzi\LaravelDoctrine\Type\Json');
```

So doctrine throws an exception saying that json type is already defined. To temporarily fix this I wrapped  that line in an if statement like this:

```php
if (!Type::hasType('json')) {
    Type::addType('json', '\Atrauzzi\LaravelDoctrine\Type\Json');
}
```

I would like to know what exactly is causing this or maybe we can just add the code I have above.

Thoughts?

**Comment by atrauzzi** [comment]
Not sure what might be causing that.  I'd prefer not to do a detection hack (it could be your project that is causing this), so it might be better if you can figure out why that's being run twice.

**Comment by mbbender** [comment]
I think this has something to do with loading the testing framework. I'm running into this problem now with Behat. I also found reference online to others having similar problems.

**Comment by mbbender** [comment]
In looking into this a bit more it appears it is related to tearing down and attempting to reboot the Laravel kernel after each test. It would seem somehow the doctrine stuff is persisting and not getting cleared out. Not sure why yet, but thought I'd share my findings.

**Comment by mbbender** [comment]
I can't find where a reference to the Type's are maintained such that the `Doctrine\DBAL\Types` class doesn't get lost when clearing out all the bindings at reboot, but it seems that @jjunqueira has the best solution since there is not `Type::reset()` or anything to clear out custom types.
