### ISSUE TITLE
Cannot install via composer

### ISSUE THREAD

**Issue by greatwitenorth** [atrauzzi/laravel-doctrine#69]
Looks like there's an issue with the migrations package:
```
atrauzzi/laravel-doctrine dev-master requires doctrine/migrations dev-master#46a031ddaea47d0685200027cfe8c83b02aee6f6 -> no matching package found.
```

Can you update your composer file?

**Comment by animexxx** [comment]
I am trying to change dev-master to master but it still not work. Anyone help?

**Comment by animexxx** [comment]
Hi greatwifenorth, I found a topic closed here: https://github.com/atrauzzi/laravel-doctrine/issues/55
It work.

**Comment by atrauzzi** [comment]
@greatwitenorth Let me know if that fixes things up for you.

**Comment by michael-bender** [comment]
@greatwitenorth Also if you do not want to make all packages pull in the dev level you can add `"doctrine/migrations":"@dev"` to your require list and when you install it will pull in only the dev version of the doctrine/migrations which is required.
