### ISSUE TITLE
No Metadata Classes to process

### ISSUE THREAD

**Issue by michael-bender** [atrauzzi/laravel-doctrine#72]
So with a base install from master and the cli-config.php in the readme I've tried creating an entity in app/Domain/Entities and just in the root app directory. I get `No Metadata Classes to process.` when I run `vendor/bin/doctrine orm:schema:create`.  How do I tell Doctrine where to find these classes with this package? Is it something I'm missing in the config? Where is it expecting to find annotated classes?

**Comment by michael-bender** [comment]
Set the config `'metadata' => [ 'driver' => 'annotation' ]`  and it is finding my entities now. If I figure out how the driver chain works and why by default it's not picking these up I'll send over a PR.

**Comment by atrauzzi** [comment]
Awesome.  Yes, if you send me any merges, I'll try to fold them in as quickly as I see them!
