### ISSUE TITLE
Artisan commands

### ISSUE THREAD

**Issue by mbbender** [atrauzzi/laravel-doctrine#82]
In poking around it seems the artisan commands are not setup to work. Is this correct or am I doing something wrong? I'm looking to try to integrate a drop/create pattern for my Behat tests and to read connection data from that environment file. I was going to start poking around the commands to get those working so I can call an Artisan::call('doctrine:schema:create') and drop from my FeatureContext (I'm new to Behat so sorry if terminology is wrong).

**Comment by atrauzzi** [comment]
I don't think I did the commands when I upgraded the pacakge for Laravel 5.  Focused mainly on just getting the configs and service providers in a workable state.
