### ISSUE TITLE
Class 'Atrauzzi\LaravelDoctrine\TablePrefix' not found (ServiceProvider.php, lines 245-246)

### ISSUE THREAD

**Issue by ntd1712** [atrauzzi/laravel-doctrine#89]
The following code is not correct, please fix it.

if ($prefix = config('doctrine.connection.prefix')) // we only have "doctrine.connections"
     $eventManager->addEventListener(Events::loadClassMetadata, new TablePrefix($prefix));
     // Class 'Atrauzzi\LaravelDoctrine\TablePrefix' not found 

--------------------------------------------------------------------------

I have to replace the original code with mine to get it work.

$connections = config('doctrine.connections');
            if ($prefix = $connections[$connections['default']]['prefix'])
                $eventManager->addEventListener(Events::loadClassMetadata, new Listener\Metadata\TablePrefix($prefix));

**Comment by ntd1712** [comment]
Can you fix this bug? Here is my Doctrine config:

<?php

return [
    'metadata' => [
        'driver' => 'annotation',
        'paths' => require __DIR__ . '/../modules/paths.php',
        'simple' => false
    ],
    'connection' => [
        'prefix' => 'tbl_'
    ],
    'connections' => [
        // Override your laravel environment database selection here if desired
        'default' => 'mysql',
        // Override your laravel values here if desired.
        'mysql' => [
            'driver' => 'pdo_mysql',
            'host' => env('DB_HOST', 'localhost'),
            'dbname' => env('DB_DATABASE', 'forge'),
            'user' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'prefix' => 'tbl_',
            'charset' => 'utf8',
            'driverOptions' => array(
                PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => true
            )
        ],
        // Some preset configurations to map laravel sqlite configs to doctrine
        'sqlite' => [
            'driver' => 'pdo_sqlite',
            'mappings' => [
                'database' => 'path'
            ]
        ]
    ],
    'cache' => [
        // Remove or set to null for no cache
        'provider' => env('CACHE_DRIVER', 'file'),
        'file' => [
            'directory' => storage_path('framework/cache'),
            'extension' => '.doctrinecache.data'
        ],
        'redis' => [
            'host' => '127.0.0.1',
            'port' => 6379,
            'database' => 1
        ],
        'memcache' => [
            'host' => '127.0.0.1',
            'port' => 11211
        ],
        'providers' => [
            'memcache' => 'Atrauzzi\LaravelDoctrine\CacheProvider\MemcacheProvider',
            'memcached' => 'Atrauzzi\LaravelDoctrine\CacheProvider\MemcachedProvider',
            'couchbase' => 'Atrauzzi\LaravelDoctrine\CacheProvider\CouchebaseProvider',
            'redis' => 'Atrauzzi\LaravelDoctrine\CacheProvider\RedisProvider',
            'apc' => 'Atrauzzi\LaravelDoctrine\CacheProvider\ApcCacheProvider',
            'xcache' => 'Atrauzzi\LaravelDoctrine\CacheProvider\XcacheProvider',
            'array' => 'Atrauzzi\LaravelDoctrine\CacheProvider\ArrayCacheProvider',
            'file' => 'Atrauzzi\LaravelDoctrine\CacheProvider\FilesystemCacheProvider'
            //'custom' => 'Path\To\Your\Class'
        ]
    ],
    'proxy_classes' => [
        'auto_generate' => 'local' === env('APP_ENV', 'local'),
        'directory' => storage_path('framework/proxies'),
        'namespace' => null,
    ],
    'migrations' => [
        'directory' => database_path('doctrine-migrations'),
        'namespace' => 'DoctrineMigrations',
        'table_name' => 'doctrine_migration_versions'
    ],
    'default_repository' => 'Doctrine\ORM\EntityRepository',
    'sql_logger' => env('APP_DEBUG', false) ? new \Doctrine\DBAL\Logging\DebugStack : null,
    'debug' => env('APP_DEBUG', false),
    'custom_types' => [
        //'json' => 'Atrauzzi\LaravelDoctrine\Type\Json'
    ],
    'auth' => [
        //'authenticator' => 'Atrauzzi\LaravelDoctrine\DoctrineAuthenticator',
        //'model' => 'App\User',
    ]
];

**Comment by josenicomaia** [comment]
What is the problem?

Can you tell me what are you trying to do?

**Comment by ntd1712** [comment]
On branch master, in file https://github.com/atrauzzi/laravel-doctrine/blob/master/src/ServiceProvider.php#L257, you create a new instance of the class " TablePrefix " without using it (e.g. " use Atrauzzi\LaravelDoctrine\TablePrex; "), so I get this error " Class 'Atrauzzi\LaravelDoctrine\TablePrefix' not found " on runtime.

**Comment by josenicomaia** [comment]
Ok, i will see it.

**Comment by josenicomaia** [comment]
PR sent =]

**Comment by ntd1712** [comment]
Thank you. Still on branch master, as you see at here https://github.com/atrauzzi/laravel-doctrine/blob/master/src/ServiceProvider.php#L258, the config "doctrine.connection.prefix" (which is used for an older version) does not exist in file vendor/atrauzzi/laravel-doctrine/config/doctrine.php

**Comment by josenicomaia** [comment]
@atrauzzi, What do you think about "doctrine.connection.prefix"?
Is it a global prefix?

**Comment by ntd1712** [comment]
As I said, it is a setting of an older version (http://github.com/atrauzzi/laravel-doctrine/commit/3935f02e0d526f6e3a347814307c7078e966d50a#diff-611fe18283f78bded6ad8e7fcccbba96R69), which is replaced with this https://github.com/atrauzzi/laravel-doctrine/blob/master/config/doctrine.php#L83

So I'd like to mention you.

Another thing, could you please create one more provider class known as " FilesystemCacheProvider.php " to " vendor/atrauzzi/laravel-doctrine/src/CacheProvider " ? This class is used by Doctrine to store data into files as cache files.

Please see the attached image for more details. Thank you.

![filesystemcacheprovider](https://cloud.githubusercontent.com/assets/1187621/8476982/b2d39e06-20f0-11e5-8e8d-369b1285d869.png)

**Comment by josenicomaia** [comment]
@ntd1712 Can you post the codes here?

**Comment by ntd1712** [comment]
Here you are :)

1- vendor/atrauzzi/laravel-doctrine/src/CacheProvider/FilesystemCacheProvider.php

```php
<?php namespace Atrauzzi\LaravelDoctrine\CacheProvider;

use Doctrine\Common\Cache\FilesystemCache;

/**
 * Class FilesystemCacheProvider
 * @package Atrauzzi\LaravelDoctrine\CacheProvider
 */
class FilesystemCacheProvider extends CacheProvider
{
    /** {@inheritdoc} */
    protected function initialize($config)
    {
        return new FilesystemCache($config['directory'], $config['extension']);
    }
}
```

2- vendor/atrauzzi/laravel-doctrine/config/doctrine.php

```php
/*
     * By default, this package mimics the cache configuration from Laravel.
     * You can create your own cache provider by extending the
     * Atrauzzi\LaravelDoctrine\CacheProvider\CacheProvider class.
     * Each provider requires a like named section with an array of configuration options
     */
    'cache' => [
        // Remove or set to null for no cache
        'provider' => env('CACHE_DRIVER', 'file'),
        'file' => [
            'directory' => storage_path('framework/cache'),
            'extension' => '.doctrinecache.data'
        ],
        'redis' => [
            'host' => '127.0.0.1',
            'port' => 6379,
            'database' => 1
        ],
        'memcache' => [
            'host' => '127.0.0.1',
            'port' => 11211
        ],
        'providers' => [
            'memcache' => 'Atrauzzi\LaravelDoctrine\CacheProvider\MemcacheProvider',
            'memcached' => 'Atrauzzi\LaravelDoctrine\CacheProvider\MemcachedProvider',
            'couchbase' => 'Atrauzzi\LaravelDoctrine\CacheProvider\CouchebaseProvider',
            'redis' => 'Atrauzzi\LaravelDoctrine\CacheProvider\RedisProvider',
            'apc' => 'Atrauzzi\LaravelDoctrine\CacheProvider\ApcCacheProvider',
            'xcache' => 'Atrauzzi\LaravelDoctrine\CacheProvider\XcacheProvider',
            'array' => 'Atrauzzi\LaravelDoctrine\CacheProvider\ArrayCacheProvider',
            'file' => 'Atrauzzi\LaravelDoctrine\CacheProvider\FilesystemCacheProvider'
            //'custom' => 'Path\To\Your\Class'
        ]
    ],
```

**Comment by josenicomaia** [comment]
In the cache.provider, i will keep
```php
'provider' => env('CACHE_DRIVER', 'array'),
```
To not impact other users.

**Comment by josenicomaia** [comment]
@ntd1712 Can you change your `composer.json` and test the changes?

```php
    "require": {
        "atrauzzi/laravel-doctrine": "dev-master-fs-cache-provider",
    },
    "repositories": [
        {
            "type": "vcs",
            "url":  "git@github.com:NicoMaia/laravel-doctrine.git"
        }
    ],
```

**Comment by ntd1712** [comment]
yes, it OK. It doesn't impact to any user. You missed the file "FilesystemCacheProvider.php", right?

**Comment by josenicomaia** [comment]
@ntd1712 Ops, my bad. File commited!

**Comment by josenicomaia** [comment]
Out to lunch. See you in a hour.

**Comment by ntd1712** [comment]
With your repository, there are 2 typo bugs in here https://github.com/NicoMaia/laravel-doctrine/blob/master/config/doctrine.php#L136:

You only have these two classes " Atrauzzi\LaravelDoctrine\CacheProvider\CouchbaseProvider " (not CouchebaseProvide) and Atrauzzi\LaravelDoctrine\CacheProvider\ApcCacheProvider::class (not ApcProvider)

**Comment by ntd1712** [comment]
Enjoy your lunch! :)

**Comment by josenicomaia** [comment]
@ntd1712 Thx. I am back =]
Fixed =]

**Comment by ntd1712** [comment]
Thank you very much =)

**Comment by josenicomaia** [comment]
@ntd1712 Is it all right? Can i send a PR to merge the branch?

**Comment by ntd1712** [comment]
Yes, it runs fine. But your branch (https://github.com/NicoMaia/laravel-doctrine/tree/master-fs-cache-provider) requires Laravel 5.1 with PHP 5.5.x, while my server only supports PHP 5.4.x. So I have to folk out another branch here https://github.com/ntd1712/laravel-doctrine.

If you have time, please take a look on my latest commits here https://github.com/ntd1712/laravel-doctrine/commits/master. And you will see they are what I ask you for help before I know about "folk" function.

Thank you again for taking your time to help me !!! =)

**Comment by josenicomaia** [comment]
@ntd1712 I understand. So, i will send the PR and i will check about PHP version. I guess it's a requirement for Lavarel 5.

Just to double check:
Is our branchs, NicoMaia.master-fs-cache-provider and ntd1712.master, are in sync (the changes)?

**Comment by josenicomaia** [comment]
I need to know this because i don't know how to test this changes.

**Comment by josenicomaia** [comment]
@ntd1712 About Laravel requirements:

5.1: PHP >= 5.5.9 (http://laravel.com/docs/5.1#installation)
5.0: PHP >= 5.4 (http://laravel.com/docs/5.0#server-requirements)

I guess we need to change composer.json to PHP 5.4 too

**Comment by ntd1712** [comment]
@josenicomaia
Yes, the branches are same :+1: 

And the answer is yes, again ;-).
Either you modify the composer.json file, or you follow this guide http://php.net/manual/en/migration55.php and modify your source code files to make them compatible with Laravel's version greater than or equal 5.0.x, for example: use 'Atrauzzi\LaravelDoctrine\CacheProvider\FilesystemCacheProvider'' instead of Atrauzzi\LaravelDoctrine\CacheProvider\FilesystemCacheProvider::class

**Comment by josenicomaia** [comment]
@ntd1712 Good Morning!!

FYI #108

**Comment by ntd1712** [comment]
:-1:

**Comment by josenicomaia** [comment]
@ntd1712 I have great news!
We are joining the developers of repositories:
https://github.com/mitchellvanw/laravel-doctrine
https://github.com/atrauzzi/laravel-doctrine
https://github.com/patrickbrouwers/Laravel-Doctrine

In just a repository = D
https://github.com/laravel-doctrine/orm

**Comment by ntd1712** [comment]
Congratulation! :100: 

With the first one, I've used it before. It's simple but it isn't good enough to me.

With the second one, it's better, but it still has bugs in the config, and it also doesn't have config for event listeners which aren't lifecycle events (that I may use to inject a service locator into my entities).

Someday, I will try to play around with the third one. :)

**Comment by josenicomaia** [comment]
@ntd1712 When the first version arrives, you should use https://github.com/laravel-doctrine/orm =]

**Comment by atrauzzi** [comment]
:)

**Comment by gmsantosxl** [comment]
@josenicomaia, @atrauzzi I'll start a project using Laravel and Doctrine.

Are there a release date this first unified version? :)
If you guys have some issue I could help, let me know.

**Comment by josenicomaia** [comment]
You can join us at Slack

http://slack.laraveldoctrine.org/

=]
